language: rust

rust:
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      script:
        # Build the with nightly version.
        - cargo build --verbose --workspace --all-features
        - cargo test --verbose --workspace --all-features

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

cache:
  cargo: true

before_script:
  - rustup component add rustfmt clippy
  - cargo clippy
  - cargo fmt

script:
  # Build with the stable version.
  - cargo build --verbose --workspace --all-features
  - cargo test --verbose --workspace --all-features

notifications:
  email: false
